name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build Samples with Java
      run: |
        cd Sample
        ./gradlew :java:assembleDebug

    - name: Build Samples with Kotlin
      run: |
        cd Sample
        ./gradlew :kotlin:assembleDebug

    - name: Uplolad apk to releases
      run: |
        mkdir apks
        mv Sample/java/build/outputs/apk/debug/java-debug.apk apks/
        mv Sample/kotlin/build/outputs/apk/debug/kotlin-debug.apk apks/
        zip -r apks.zip apks/

        .github/workflows/upload_releases.sh `echo ${GITHUB_SHA##*/}`
      env:
        TOKEN: ${{ secrets.UPLOAD_TOKEN }}
